stages:
- test

test:
  stage: test
  tags: [docker]
  image: golang:1.20.5-alpine3.17
  before_script:
    - apk add --update py3-psutil python3-dev && ln -sf python3 /usr/bin/python && python3 -m ensurepip
    - pip3 install -U pip requests
  script:
    - go test
