repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
        # - id: go-unit-tests
      - id: go-mod-tidy

  - repo: https://github.com/rivosinc/reuse-tool
    rev: 'b512b7b19fd56388eda5f0c7a8ea6c2ad094109f'
    hooks:
      # Check compliance
      - id: reuse